# LeetCode
# Problem 895. Maximum Frequency Stack
# https://leetcode.com/problems/maximum-frequency-stack/description/

cc_library(
    name = "max_freq_stack",
    srcs = ["max_freq_stack.cc"],
    hdrs = ["max_freq_stack.h"],
)

cc_test(
    name = "max_freq_stack_test",
    size = "small",
    srcs = ["max_freq_stack_test.cc"],
    deps = [
        ":max_freq_stack",
        "@googletest//:gtest_main",
    ],
)
