# CodeForces Round 1050 Div. 4
# Problem E. Split
# https://codeforces.com/problemset/problem/2148/E

cc_library(
    name = "split",
    srcs = ["split.cc"],
    hdrs = ["split.h"],
)

cc_test(
    name = "split_test",
    size = "small",
    srcs = ["split_test.cc"],
    deps = [
        ":split",
        "@googletest//:gtest_main",
    ],
)
