# LeetCode
# Problem 3664. Two-Letter Card Game
# https://leetcode.com/problems/two-letter-card-game/description

cc_library(
    name = "two_letter_card_game",
    srcs = ["two_letter_card_game.cc"],
    hdrs = ["two_letter_card_game.h"],
)

cc_test(
    name = "two_letter_card_game_test",
    size = "small",
    srcs = ["two_letter_card_game_test.cc"],
    deps = [
        ":two_letter_card_game",
        "@googletest//:gtest_main",
    ],
)
