java_binary(
    name = "circus",
    srcs = ["Circus.java"],
    main_class = "codeforces.beta01.Circus",
)

java_binary(
    name = "spreadsheets",
    srcs = ["Spreadsheets.java"],
    main_class = "codeforces.beta01.Spreadsheets",
)

java_binary(
    name = "theater_square",
    srcs = ["TheaterSquare.java"],
    main_class = "codeforces.beta01.TheaterSquare",
)
